[tool.poetry]
name = "sharp-cocoro"
version = "0.1.0"
description = "A Python SDK for the Cocoro API"
authors = ["David Mohl <git@d.sh>"]
license = "MIT"
readme = "README.md"
packages = [{include = "sharp_cocoro"}]

[tool.poetry.dependencies]
aiohttp = "3.9.5"
aiosignal = "1.3.1"
attrs = "23.2.0"
certifi = "2024.6.2"
charset-normalizer = "3.3.2"
frozenlist = "1.4.1"
idna = "3.7"
multidict = "6.0.5"
pydantic = "1.10.17"
yarl = "1.9.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"