[tool.poetry]
name = "sharp-cocoro"
version = "0.1.0"
description = "A Python SDK for the Cocoro API"
authors = ["David Mohl <git@d.sh>"]
license = "MIT"
readme = "README.md"
packages = [{include = "sharp_cocoro"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
pydantic = "^1.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"